### ISSUE TITLE
调用i18n-collect-cli tojs 1.xlsx 1.js，报错‘1.xlsx文件不存在’

### ISSUE THREAD

**Issue by liuyeqing** [xujiujiu/i18n-collect-cli#11]

**Comment by xujiujiu** [comment]
你看一下你执行目录的pwd呢？pwd对应的执行目录下有你的1.xlsx文件吗？

**Comment by liuyeqing** [comment]
1.xlsx不是运行命令所在文件夹层级吗？
![image](https://github.com/user-attachments/assets/be77efe4-9f66-404f-936e-b91ec2afdbca)

**Comment by xujiujiu** [comment]
看了下，目前你那边只能使用i18n-collect-cli tojs /1.xlsx /1.js，后续改一下路径识别
